# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node install
        uses: actions/setup-node@v2
      - run: npm install   
      - name: Wait 20s
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - run: git clone https://github.com/juice-shop/juice-shop.git
      - run: cd juice-shop
      - run: npm install
      - run: npm start
      - name: Wait 20s
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'      
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'http://localhost:3000'
