name: zapfull-security-scan
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
          issue_title: Vulnerability Scan Results
          docker_name: owasp/zap2docker-weekly
          target: "http://127.0.0.1/app"
          rules_file_name: .github/zap.ignore
          cmd_options: '-a'
          
          http_login_form: '/app/login'
          http_login_http_username: 'admin'
          http_login_http_password: 'admin'				
